      SUBROUTINE readvub
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      41   
*     Ntuple Title:   NEW_NTUPLE
*     Creation:       10/06/2025 16.27.19
*
*********************************************************
*
      REAL Ecm,Acol,Acop,ANGiso,Thrust,THthru,FIthru,Pvis,Prad,PTmiss
     + ,Eemtot,Eemneu,Erad,Evis,Ehatot,Ehaneu
      INTEGER NRrun,Ievent,NRfilsq,RunQL
      COMMON /EVENT/ NRrun,Ievent,NRfilsq,Ecm,RunQL,Acol,Acop,ANGiso
     + ,Thrust,THthru,FIthru,Pvis,Prad,PTmiss,Eemtot,Eemneu,Erad,Evis
     + ,Ehatot,Ehaneu
*
      INTEGER NVDHIT
      COMMON / VDGLOB/ NVDHIT
*
      INTEGER GenTop
      COMMON /SIMTOP/ GenTop
*
      REAL PTauH1,ThTauH1,FiTauH1,PPMcH1,THMcH1,FIMcH1
      INTEGER DeTH1,PolH1,NMcH1,nMcTH1,CXMcH1,CMMcH1
      COMMON /SIMH1/ PTauH1,ThTauH1,FiTauH1,DeTH1,PolH1,NMcH1,nMcTH1
     + ,CXMcH1(15),CMMcH1(15),PPMcH1(15),THMcH1(15),FIMcH1(15)
*
      REAL PTauH2,ThTauH2,FiTauH2,PPMcH2,THMcH2,FIMcH2
      INTEGER DeTH2,PolH2,NMcH2,nMcTH2,CXMcH2,CMMcH2
      COMMON /SIMH2/ PTauH2,ThTauH2,FiTauH2,DeTH2,PolH2,NMcH2,nMcTH2
     + ,CXMcH2(15),CMMcH2(15),PPMcH2(15),THMcH2(15),FIMcH2(15)
*
      REAL PQH1,TheH1,FiH1,EeH1,RadH1,dEdxH1,EemH1,EHaH1,trLeH1,ZimpH1
     + ,RimpH1,DPpH1,DThH1,DFiH1,DEeH1,SdEdxH1,TaEmH1,FaEmH1,ThEmH1
     + ,FiEmH1,E1EmH1,E2EmH1,E3EmH1,E4EmH1,E5EmH1,E6EmH1,E7EmH1,E8EmH1
     + ,E9EmH1,E1HaH1,E2HaH1,E3HaH1,E4HaH1
      INTEGER NChaH1,NProH1,NEmNH1,NHaNH1,McodH1,NVdH1
      COMMON /HEMI1/ NChaH1,NProH1,NEmNH1,NHaNH1,PQH1(7),TheH1(7)
     + ,FiH1(7),McodH1(7),EeH1(7),RadH1(7),dEdxH1(7),EemH1(7),EHaH1(7)
     + ,trLeH1(7),ZimpH1(7),RimpH1(7),DPpH1(7),DThH1(7),DFiH1(7)
     + ,DEeH1(7),SdEdxH1(7),NVdH1(7),TaEmH1(7),FaEmH1(7),ThEmH1(7)
     + ,FiEmH1(7),E1EmH1(7),E2EmH1(7),E3EmH1(7),E4EmH1(7),E5EmH1(7)
     + ,E6EmH1(7),E7EmH1(7),E8EmH1(7),E9EmH1(7),E1HaH1(7),E2HaH1(7)
     + ,E3HaH1(7),E4HaH1(7)
*
      REAL EEmNH1,THeNH1,FiNH1,E1NH1,E2NH1,E3NH1,E4NH1,E5NH1,E6NH1,E7NH1
     + ,E8NH1,E9NH1,EHaHH1,THeHH1,FiHH1
      INTEGER NrEmNH1,McoNH1,NrHaNH1,McoHH1,NHaLNH1
      COMMON /NEUH1/ NrEmNH1,EEmNH1(7),THeNH1(7),FiNH1(7),McoNH1(7)
     + ,E1NH1(7),E2NH1(7),E3NH1(7),E4NH1(7),E5NH1(7),E6NH1(7),E7NH1(7)
     + ,E8NH1(7),E9NH1(7),NrHaNH1,EHaHH1(5),THeHH1(5),FiHH1(5),McoHH1(5)
     + ,NHaLNH1(5)
*
      REAL xP1VdH1,yP1VdH1,RP1VdH1,PhiVdH1
      INTEGER NrAsH1
      COMMON /VDASH1/ NrAsH1,xP1VdH1(6),yP1VdH1(6),RP1VdH1(6),PhiVdH1(6)
*
      REAL PQH2,TheH2,FiH2,EeH2,RadH2,dEdxH2,EemH2,EHaH2,trLeH2,ZimpH2
     + ,RimpH2,DPpH2,DThH2,DFiH2,DEeH2,SdEdxH2,TaEmH2,FaEmH2,ThEmH2
     + ,FiEmH2,E1EmH2,E2EmH2,E3EmH2,E4EmH2,E5EmH2,E6EmH2,E7EmH2,E8EmH2
     + ,E9EmH2,E1HaH2,E2HaH2,E3HaH2,E4HaH2
      INTEGER NChaH2,NProH2,NEmNH2,NHaNH2,McodH2,NVdH2
      COMMON /HEMI2/ NChaH2,NProH2,NEmNH2,NHaNH2,PQH2(7),TheH2(7)
     + ,FiH2(7),McodH2(7),EeH2(7),RadH2(7),dEdxH2(7),EemH2(7),EHaH2(7)
     + ,trLeH2(7),ZimpH2(7),RimpH2(7),DPpH2(7),DThH2(7),DFiH2(7)
     + ,DEeH2(7),SdEdxH2(7),NVdH2(7),TaEmH2(7),FaEmH2(7),ThEmH2(7)
     + ,FiEmH2(7),E1EmH2(7),E2EmH2(7),E3EmH2(7),E4EmH2(7),E5EmH2(7)
     + ,E6EmH2(7),E7EmH2(7),E8EmH2(7),E9EmH2(7),E1HaH2(7),E2HaH2(7)
     + ,E3HaH2(7),E4HaH2(7)
*
      REAL EEmNH2,THeNH2,FiNH2,E1NH2,E2NH2,E3NH2,E4NH2,E5NH2,E6NH2,E7NH2
     + ,E8NH2,E9NH2,EHaHH2,THeHH2,FiHH2
      INTEGER NrEmNH2,McoNH2,NrHaNH2,McoHH2,NHaLNH2
      COMMON /NEUH2/ NrEmNH2,EEmNH2(7),THeNH2(7),FiNH2(7),McoNH2(7)
     + ,E1NH2(7),E2NH2(7),E3NH2(7),E4NH2(7),E5NH2(7),E6NH2(7),E7NH2(7)
     + ,E8NH2(7),E9NH2(7),NrHaNH2,EHaHH2(5),THeHH2(5),FiHH2(5),McoHH2(7)
     + ,NHaLNH2(5)
*
      REAL xP1VdH2,yP1VdH2,RP1VdH2,PhiVdH2
      INTEGER NrAsH2
      COMMON /VDASH2/ NrAsH2,xP1VdH2(6),yP1VdH2(6),RP1VdH2(6),PhiVdH2(6)
*
      CALL HBNAME(41,' ',0,'$CLEAR')
      CALL HBNAME(41,'EVENT',NRrun,'$SET')
*
      CALL HBNAME(41,' VDGLOB',NVDHIT,'$SET')
*
      CALL HBNAME(41,'SIMTOP',GenTop,'$SET')
*
      CALL HBNAME(41,'SIMH1',PTauH1,'$SET')
*
      CALL HBNAME(41,'SIMH2',PTauH2,'$SET')
*
      CALL HBNAME(41,'HEMI1',NChaH1,'$SET')
*
      CALL HBNAME(41,'NEUH1',NrEmNH1,'$SET')
*
      CALL HBNAME(41,'VDASH1',NrAsH1,'$SET')
*
      CALL HBNAME(41,'HEMI2',NChaH2,'$SET')
*
      CALL HBNAME(41,'NEUH2',NrEmNH2,'$SET')
*
      CALL HBNAME(41,'VDASH2',NrAsH2,'$SET')
*

*
*--   Enter user code here
*

*
      END
